name: OmniPuzzle
version: '1.0'
api-version: '1.15'
main: net.omni.puzzle.PuzzlePlugin
description: A puzzle plugin.
author: omni
softdepend:
  - PlaceholderAPI
commands:
  puzzle:
    usage: /<command>
    description: The main command.